#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="$ROOT_DIR/XPO-ATS/.env.local"
OUT_FILE="${1:-$ROOT_DIR/migrations/live_supabase_schema_2026-03-11.sql}"
GENERATED_ON="$(date +%F)"

if [[ ! -f "$ENV_FILE" ]]; then
  echo "Missing env file: $ENV_FILE" >&2
  exit 1
fi

source "$ENV_FILE"

if [[ -z "${DATABASE_URL:-}" ]]; then
  echo "DATABASE_URL is not set in $ENV_FILE" >&2
  exit 1
fi

mkdir -p "$(dirname "$OUT_FILE")"

cat >"$OUT_FILE" <<SQL
-- Live Supabase public schema snapshot
-- Generated from the remote database catalog.
-- Date: $GENERATED_ON
-- Note:
--   This file was generated without pg_dump because the local pg_dump version
--   is older than the remote server and Supabase CLI dump requires Docker.
--   It is intended as a reliable schema snapshot for review and migration work.

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

SQL

append_query() {
  local title="$1"
  local sql="$2"

  {
    printf '\n-- %s\n\n' "$title"
    psql "$DATABASE_URL" -X -q -v ON_ERROR_STOP=1 -At <<SQL
$sql
SQL
  } >>"$OUT_FILE"
}

append_query "Sequences" "
SELECT format(
  'CREATE SEQUENCE public.%I AS %s START WITH %s INCREMENT BY %s MINVALUE %s MAXVALUE %s CACHE %s;',
  c.relname,
  pg_catalog.format_type(s.seqtypid, NULL),
  s.seqstart,
  s.seqincrement,
  s.seqmin,
  s.seqmax,
  s.seqcache
)
FROM pg_sequence s
JOIN pg_class c ON c.oid = s.seqrelid
JOIN pg_namespace n ON n.oid = c.relnamespace
WHERE n.nspname = 'public'
ORDER BY c.relname;
"

append_query "Tables" "
SELECT
  'CREATE TABLE public.' || quote_ident(c.relname) || E' (\n' ||
  string_agg(
    '    ' || quote_ident(a.attname) || ' ' || pg_catalog.format_type(a.atttypid, a.atttypmod) ||
    CASE
      WHEN a.attidentity = 'a' THEN ' GENERATED ALWAYS AS IDENTITY'
      WHEN a.attidentity = 'd' THEN ' GENERATED BY DEFAULT AS IDENTITY'
      ELSE ''
    END ||
    CASE
      WHEN ad.adbin IS NOT NULL THEN ' DEFAULT ' || pg_get_expr(ad.adbin, ad.adrelid)
      ELSE ''
    END ||
    CASE
      WHEN a.attnotnull THEN ' NOT NULL'
      ELSE ''
    END,
    E',\n'
    ORDER BY a.attnum
  ) ||
  E'\n);'
FROM pg_class c
JOIN pg_namespace n ON n.oid = c.relnamespace
JOIN pg_attribute a ON a.attrelid = c.oid
LEFT JOIN pg_attrdef ad ON ad.adrelid = c.oid AND ad.adnum = a.attnum
WHERE n.nspname = 'public'
  AND c.relkind = 'r'
  AND a.attnum > 0
  AND NOT a.attisdropped
GROUP BY c.relname
ORDER BY c.relname;
"

append_query "Sequence Ownership" "
SELECT format(
  'ALTER SEQUENCE public.%I OWNED BY public.%I.%I;',
  seq.relname,
  tbl.relname,
  att.attname
)
FROM pg_class seq
JOIN pg_namespace seq_ns ON seq_ns.oid = seq.relnamespace
JOIN pg_depend dep ON dep.objid = seq.oid AND dep.deptype = 'a'
JOIN pg_class tbl ON tbl.oid = dep.refobjid
JOIN pg_namespace tbl_ns ON tbl_ns.oid = tbl.relnamespace
JOIN pg_attribute att ON att.attrelid = tbl.oid AND att.attnum = dep.refobjsubid
WHERE seq.relkind = 'S'
  AND seq_ns.nspname = 'public'
  AND tbl_ns.nspname = 'public'
ORDER BY seq.relname;
"

append_query "Constraints" "
SELECT format(
  'ALTER TABLE ONLY public.%I ADD CONSTRAINT %I %s;',
  cls.relname,
  con.conname,
  pg_get_constraintdef(con.oid)
)
FROM pg_constraint con
JOIN pg_class cls ON cls.oid = con.conrelid
JOIN pg_namespace nsp ON nsp.oid = cls.relnamespace
WHERE nsp.nspname = 'public'
ORDER BY cls.relname, con.contype, con.conname;
"

append_query "Indexes" "
SELECT pg_get_indexdef(idx.indexrelid) || ';'
FROM pg_index idx
JOIN pg_class tbl ON tbl.oid = idx.indrelid
JOIN pg_namespace nsp ON nsp.oid = tbl.relnamespace
LEFT JOIN pg_constraint con ON con.conindid = idx.indexrelid
WHERE nsp.nspname = 'public'
  AND con.oid IS NULL
ORDER BY tbl.relname, idx.indexrelid;
"

append_query "Functions" "
SELECT pg_get_functiondef(proc.oid)
FROM pg_proc proc
JOIN pg_namespace nsp ON nsp.oid = proc.pronamespace
WHERE nsp.nspname = 'public'
ORDER BY proc.proname;
"

append_query "Triggers" "
SELECT pg_get_triggerdef(trg.oid, true) || ';'
FROM pg_trigger trg
JOIN pg_class cls ON cls.oid = trg.tgrelid
JOIN pg_namespace nsp ON nsp.oid = cls.relnamespace
WHERE nsp.nspname = 'public'
  AND NOT trg.tgisinternal
ORDER BY cls.relname, trg.tgname;
"

append_query "Row Level Security" "
SELECT format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY;', cls.relname)
FROM pg_class cls
JOIN pg_namespace nsp ON nsp.oid = cls.relnamespace
WHERE nsp.nspname = 'public'
  AND cls.relkind = 'r'
  AND cls.relrowsecurity
ORDER BY cls.relname;
"

append_query "Policies" "
SELECT format(
  'CREATE POLICY %I ON public.%I AS %s FOR %s TO %s%s%s;',
  pol.policyname,
  pol.tablename,
  pol.permissive,
  pol.cmd,
  CASE
    WHEN array_length(pol.roles, 1) IS NULL THEN 'PUBLIC'
    ELSE array_to_string(ARRAY(SELECT quote_ident(role_name) FROM unnest(pol.roles) AS role_name), ', ')
  END,
  CASE
    WHEN pol.qual IS NOT NULL THEN format(' USING (%s)', pol.qual)
    ELSE ''
  END,
  CASE
    WHEN pol.with_check IS NOT NULL THEN format(' WITH CHECK (%s)', pol.with_check)
    ELSE ''
  END
)
FROM pg_policies pol
WHERE pol.schemaname = 'public'
ORDER BY pol.tablename, pol.policyname;
"

echo "Wrote schema snapshot to $OUT_FILE"
