-- Live Supabase public schema snapshot
-- Generated from the remote database catalog.
-- Date: 2026-03-12
-- Note:
--   This file was generated without pg_dump because the local pg_dump version
--   is older than the remote server and Supabase CLI dump requires Docker.
--   It is intended as a reliable schema snapshot for review and migration work.

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";


-- Sequences

CREATE SEQUENCE public.campaign_subscription_id_seq AS bigint START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1;
CREATE SEQUENCE public.campaign_trigger_id_seq AS bigint START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1;
CREATE SEQUENCE public.candidate_skill_map_id_seq AS bigint START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1;
CREATE SEQUENCE public.difficulties_id_seq AS integer START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1;
CREATE SEQUENCE public.naukri_candidate_id_seq AS bigint START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1;
CREATE SEQUENCE public.openai_call_logs_id_seq AS bigint START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1;
CREATE SEQUENCE public.skill_level_master_id_seq AS bigint START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1;
CREATE SEQUENCE public.skill_map_id_seq AS bigint START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1;
CREATE SEQUENCE public.skill_master_id_seq AS bigint START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1;

-- Tables

CREATE TABLE public.app_tokens (
    id text DEFAULT 'ms_graph_tokens'::text NOT NULL,
    token_data jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);
CREATE TABLE public.applications_id (
    id uuid DEFAULT uuid_generate_v4() NOT NULL,
    airtable_id text NOT NULL,
    vendor_id uuid,
    openings_id uuid,
    status character varying(100),
    internal_screening_time_and_date date,
    sow_signed_with_client_date character varying(255),
    sow_signed_with_vendor_date character varying(255),
    clients_onboarding_date character varying(255),
    status_remarks text,
    next_task character varying(100),
    link_post_interview_questionnaire text,
    status_post_interview_questionnaire character varying(100),
    clients_feedback_status character varying(100),
    screening_fathom_links text,
    other_offers text,
    screening_report_link text,
    candidates_preferred_slot text,
    created_time timestamp with time zone DEFAULT now(),
    send_mail boolean DEFAULT false,
    followup_email_status character varying(100),
    experience_level_candidate character varying(100),
    clients_interview_feedback text,
    fnt_post_interview text,
    last_modified timestamp with time zone DEFAULT now(),
    form_filled_by character varying(255),
    lwd date,
    follow_up_date date,
    update_airtable boolean DEFAULT false,
    pre_l1_transcript text,
    post_screening_report text,
    screening_clear_date date,
    transcript text,
    pid_taken_by_id uuid,
    vs_remarks text,
    profiles_database_id uuid,
    send_to_client character varying(100),
    revised_ctc_lpa numeric(12,2),
    morning_followup_status character varying(100),
    panel_type character varying(100),
    tech_screening text,
    cluely_report text,
    backup_candidate character varying(100),
    tracker_remarks text,
    cv_sent_to_client_date timestamp with time zone,
    cv_sent_to_client_date_last_updated timestamp with time zone,
    name_as_per_the_aadhar text,
    backup_option_1 text,
    vendor_of_option_1 text,
    backup_option_2 text,
    vendor_of_option_2 text,
    id_type_submitted text,
    opening_vendor_summary character varying(255),
    scheduling_coordination_started character varying(100),
    interview_coordination character varying(100),
    candidate_followup character varying(100),
    offboarding character varying(100),
    offboarding_status character varying(100),
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);
CREATE TABLE public.campaign_subscription (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    unique_id text NOT NULL,
    campaign_id text NOT NULL,
    subscription_id text NOT NULL,
    event_date timestamp with time zone NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE public.campaign_trigger (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    campaign_id text NOT NULL,
    condition jsonb DEFAULT '{}'::jsonb,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    is_active boolean DEFAULT false NOT NULL,
    field_conversions jsonb,
    "offset" bigint
);
CREATE TABLE public.candidate_skill_map (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    candidate_id text NOT NULL,
    skill_id bigint NOT NULL,
    self_rating integer,
    number_of_projects integer DEFAULT 0,
    created_at timestamp with time zone DEFAULT now(),
    summary jsonb,
    assessed boolean,
    skill_rating_assessment jsonb,
    conceptual_rating real,
    practical_rating real,
    coding_rating real,
    overall_rating integer,
    pre_screening_ai_rating integer,
    skills_violation_justification text,
    pre_screening_ai_summary jsonb
);
CREATE TABLE public.client_department (
    id uuid DEFAULT uuid_generate_v4() NOT NULL,
    airtable_id text NOT NULL,
    department_name character varying(255),
    department_id integer,
    client_name_id uuid,
    primary_poc character varying(255),
    primary_poc_phone_number character varying(50),
    primary_poc_role character varying(255),
    secondary_poc character varying(255),
    secondary_poc_phone_number character varying(50),
    secondary_poc_role character varying(255),
    primary_poc_email_id character varying(255),
    secondary_poc_email_id character varying(255),
    document_type character varying(255),
    phone_screening_questionnaire text,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);
CREATE TABLE public.client_master (
    id uuid DEFAULT uuid_generate_v4() NOT NULL,
    airtable_id text NOT NULL,
    client_name character varying(255),
    client_industry character varying(255),
    contact_email character varying(255),
    contact_phone character varying(50),
    spoc character varying(255),
    client_requirements character varying(255),
    location character varying(100),
    requirements_type character varying(100),
    linkedin_url text,
    client_id integer,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    location_id uuid
);
CREATE TABLE public.difficulties (
    id integer DEFAULT nextval('difficulties_id_seq'::regclass) NOT NULL,
    level_name text NOT NULL
);
CREATE TABLE public.locations (
    id uuid DEFAULT uuid_generate_v4() NOT NULL,
    airtable_id text NOT NULL,
    name character varying(255),
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);
CREATE TABLE public.naukri_candidates (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    airtable_record_id text,
    unique_candidate_id text NOT NULL,
    folder_id uuid,
    candidate_name text,
    email text,
    phone text,
    experience text,
    current_ctc text,
    expected_ctc text,
    current_designation text,
    highest_education text,
    current_location text,
    preferred_location text,
    naukri_profile_link text,
    screening_report_link text,
    screening_report_summary text,
    folder_description text,
    match_score integer DEFAULT 0,
    status text DEFAULT 'Candidate Created'::text,
    resume_json jsonb,
    logs jsonb DEFAULT '[]'::jsonb,
    vendor_name text,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    draft_created boolean DEFAULT false,
    draft_created_time timestamp with time zone,
    candidate_id text,
    candidate_created boolean DEFAULT false
);
CREATE TABLE public.naukri_folders (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    airtable_record_id text,
    folder_id text NOT NULL,
    folder_name text NOT NULL,
    description text,
    opening_id text,
    vendor_id text,
    vendor_id_number integer,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);
CREATE TABLE public.onboarding_events (
    id uuid DEFAULT uuid_generate_v4() NOT NULL,
    selected_id uuid NOT NULL,
    event_type character varying(50) NOT NULL,
    event_date date,
    status character varying(100),
    notes text,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);
CREATE TABLE public.openai_call_logs (
    id bigint DEFAULT nextval('openai_call_logs_id_seq'::regclass) NOT NULL,
    "timestamp" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    operation character varying(50) NOT NULL,
    candidate_id character varying(255),
    candidate_name character varying(255),
    screening_id character varying(255),
    status character varying(50) NOT NULL,
    model character varying(100),
    error_message text,
    error_code character varying(100),
    http_status integer,
    duration_ms integer,
    request_metadata jsonb,
    retry_count integer DEFAULT 0,
    last_retry_time timestamp with time zone,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE TABLE public.openings (
    id uuid DEFAULT uuid_generate_v4() NOT NULL,
    airtable_id text NOT NULL,
    job_title text,
    opening_id integer,
    client_department_id uuid,
    client_id uuid,
    experience_level text,
    number_of_open_position numeric,
    job_description text,
    status character varying(100),
    client_billing numeric(12,2),
    duration_months numeric,
    date_opened date,
    onboarding_process_notes text,
    comments text,
    raw_jd_from_client jsonb,
    bline_id character varying(100),
    ctc_lpa_limit_eg_14 text,
    is_exclusive character varying(100),
    max_vendor_budget numeric(12,2),
    screeners_profile character varying(255),
    jd_for_prompt text,
    candidate_type character varying(100),
    job_group text[],
    job_id numeric,
    interview_slots text,
    questionnaire text,
    master_pid_document text,
    recruitment_target_ctc numeric(12,2),
    naukri_folder text,
    maximum_joining_period_days numeric,
    maximum_notice_period_allowed numeric,
    partner_recruitment_fees_of_annual_ctc numeric(5,2),
    coding_q1 text,
    coding_q2 text,
    skill_coding_q1 text,
    skill_coding_q2 text,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    temp_client_department text,
    temp_client text,
    job_visibility character varying(100),
    job_bench_type character varying(100),
    advisory text,
    sync_status text DEFAULT 'SYNCED'::text,
    last_sync_attempt timestamp with time zone,
    sync_error_details text
);
CREATE TABLE public.openings_locations_openings (
    openings_id uuid NOT NULL,
    locations_id uuid NOT NULL
);
CREATE TABLE public.profiles_database (
    id uuid DEFAULT uuid_generate_v4() NOT NULL,
    airtable_id text NOT NULL,
    candidate_id text,
    creation_date timestamp with time zone,
    skill text,
    candidate_name text,
    cv_link text,
    candidate_contact numeric,
    candidate_email text,
    current_company text,
    notice_period text,
    current_location text,
    preferred_location character varying(100),
    ctc_lpa numeric(12,2),
    ectc_lpa numeric(12,2),
    candidate_cost numeric(12,2),
    bench_type character varying(100),
    location_id uuid,
    govt_id text,
    communication_rating integer,
    confidence_rating integer,
    tech_self_rating text,
    comments text,
    last_working_day date,
    candidate_type character varying(100),
    vendors_id uuid,
    screening_report text,
    autonumber integer,
    career_gap text,
    edited_cv text,
    edited_psr text,
    lyncogs text,
    lyncogs_summary text,
    is_resigned boolean DEFAULT false,
    candidate_document text,
    type_of_id text,
    recruitment_notes text,
    is_draft boolean DEFAULT false,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    project_summary text,
    employment_history text,
    gap_analysis text,
    jumping_frequency numeric,
    extracted_skills text,
    sync_status character varying(100),
    last_sync_at timestamp with time zone,
    sync_error text
);
CREATE TABLE public.questions (
    id text DEFAULT nanoid(12) NOT NULL,
    question_text text NOT NULL,
    skill_id bigint,
    difficulty_id integer
);
CREATE TABLE public.ranking_jobs (
    id uuid DEFAULT uuid_generate_v4() NOT NULL,
    job_id integer NOT NULL,
    jd text NOT NULL,
    status text DEFAULT 'pending'::text NOT NULL,
    to_rank jsonb NOT NULL,
    results jsonb,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    error_message text
);
CREATE TABLE public.rooms (
    id uuid DEFAULT uuid_generate_v4() NOT NULL,
    room_name text,
    daily_start_time time without time zone,
    daily_end_time time without time zone,
    days_of_week text[] DEFAULT '{}'::text[],
    slot_duration_minutes integer DEFAULT 30,
    is_active boolean DEFAULT true,
    meeting_link text,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);
CREATE TABLE public.screener_assignments (
    screener_id uuid NOT NULL,
    application_id uuid NOT NULL,
    role character varying(50) NOT NULL,
    assigned_at timestamp with time zone DEFAULT now()
);
CREATE TABLE public.screeners_profile (
    id uuid DEFAULT uuid_generate_v4() NOT NULL,
    airtable_id text NOT NULL,
    name character varying(255),
    number character varying(50),
    status character varying(100),
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    vendor_id uuid
);
CREATE TABLE public.screenings (
    id uuid DEFAULT uuid_generate_v4() NOT NULL,
    airtable_id text NOT NULL,
    candidate_name character varying(255),
    candidate_id uuid,
    date timestamp with time zone,
    meeting_link text,
    skill text,
    cv_link text,
    organizer_email text,
    vendor_id uuid,
    event_created_time timestamp with time zone,
    fetched_time timestamp with time zone DEFAULT now(),
    screener_assigned character varying(255),
    created_email text,
    event_id text,
    last_modified timestamp with time zone DEFAULT now(),
    created_time timestamp with time zone DEFAULT now(),
    status character varying(100),
    comments text,
    ai_interview_link text,
    slotkey character varying(255),
    admin_interview_link text,
    application_id uuid,
    test_date timestamp with time zone,
    screener_evaluation_report text,
    answer_of_coding_q1 text,
    answer_of_coding_q2 text,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    candidate_profile_id uuid,
    screener_audit_report text,
    interview_breadth_rating numeric(3,2),
    interview_depth_rating numeric(3,2),
    sop_flow_adherence_rating numeric(3,2),
    communication_quality_rating numeric(3,2),
    overall_screening_effectiveness_rating numeric(3,2),
    room_id uuid
);
CREATE TABLE public.selected_candidates (
    id uuid DEFAULT uuid_generate_v4() NOT NULL,
    airtable_id text NOT NULL,
    candidate_from_applications_id uuid,
    assignee character varying(255),
    status character varying(100),
    attachments jsonb,
    selection_date date,
    overall_status character varying(100),
    pf_status character varying(100),
    pf_doc_remarks text,
    university_docs_check character varying(100),
    university_docs_remarks text,
    whose_bench_id uuid,
    finalised_ctc_eg_1200000 numeric(12,2),
    is_this_fte character varying(100),
    invoice_raised character varying(100),
    crc_confirmation_date date,
    offboarding character varying(100),
    offboarding_status character varying(100),
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);
CREATE TABLE public.skill_level_master (
    id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
    level text NOT NULL
);
CREATE TABLE public.skill_map (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    opening_id integer NOT NULL,
    skill_id bigint,
    level_id bigint
);
CREATE TABLE public.skill_master (
    id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
    skill_name text NOT NULL
);
CREATE TABLE public.skill_sets (
    id text DEFAULT nanoid(12) NOT NULL,
    skill_name text NOT NULL,
    questions jsonb DEFAULT '[]'::jsonb NOT NULL
);
CREATE TABLE public.status_config (
    id uuid DEFAULT uuid_generate_v4() NOT NULL,
    domain character varying(50) NOT NULL,
    code character varying(100) NOT NULL,
    label text NOT NULL,
    color_hex character varying(7),
    is_terminal boolean DEFAULT false,
    sort_order smallint DEFAULT 0,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);
CREATE TABLE public.users (
    id uuid DEFAULT uuid_generate_v4() NOT NULL,
    airtable_id text NOT NULL,
    username text,
    password text,
    type character varying(100),
    screener_link text,
    namemanual_entry text,
    pid_authorization character varying(100),
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    screener_profile_id uuid
);
CREATE TABLE public.vendor_master (
    id uuid DEFAULT uuid_generate_v4() NOT NULL,
    airtable_id text NOT NULL,
    vendor_name text,
    vendor_address text,
    vendor_registration_date date,
    vendor_profiles text,
    resource_location character varying(100),
    linkedin_url text,
    vendor_status character varying(100),
    vendor_id_number numeric,
    revenue_model character varying(100),
    vendor_poc character varying(255),
    poc_contact_number character varying(50),
    poc_mail_id character varying(255),
    additional_poc_mail_ids text,
    password character varying(255),
    vendor_type character varying(100),
    master_pid_document text,
    status character varying(100),
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);
CREATE TABLE public.vendor_openings (
    vendor_id uuid NOT NULL,
    opening_id uuid NOT NULL,
    is_exclusive boolean DEFAULT false NOT NULL,
    assigned_at timestamp with time zone DEFAULT now()
);

-- Sequence Ownership

ALTER SEQUENCE public.difficulties_id_seq OWNED BY public.difficulties.id;
ALTER SEQUENCE public.openai_call_logs_id_seq OWNED BY public.openai_call_logs.id;

-- Constraints

ALTER TABLE ONLY public.app_tokens ADD CONSTRAINT app_tokens_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.applications_id ADD CONSTRAINT fk_applications_id_openings_id FOREIGN KEY (openings_id) REFERENCES openings(id);
ALTER TABLE ONLY public.applications_id ADD CONSTRAINT fk_applications_id_pid_taken_by_id FOREIGN KEY (pid_taken_by_id) REFERENCES users(id);
ALTER TABLE ONLY public.applications_id ADD CONSTRAINT fk_applications_id_profiles_database_id FOREIGN KEY (profiles_database_id) REFERENCES profiles_database(id);
ALTER TABLE ONLY public.applications_id ADD CONSTRAINT fk_applications_id_vendor_id FOREIGN KEY (vendor_id) REFERENCES vendor_master(id);
ALTER TABLE ONLY public.applications_id ADD CONSTRAINT applications_id_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.applications_id ADD CONSTRAINT applications_id_airtable_id_key UNIQUE (airtable_id);
ALTER TABLE ONLY public.campaign_subscription ADD CONSTRAINT campaign_subscription_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.campaign_trigger ADD CONSTRAINT campaign_trigger_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.candidate_skill_map ADD CONSTRAINT candidate_skill_map_overall_rating_check CHECK (((overall_rating >= 1) AND (overall_rating <= 5)));
ALTER TABLE ONLY public.candidate_skill_map ADD CONSTRAINT candidate_skill_map_pre_screening_ai_rating_check CHECK (((pre_screening_ai_rating >= 0) AND (pre_screening_ai_rating <= 5)));
ALTER TABLE ONLY public.candidate_skill_map ADD CONSTRAINT candidate_skill_map_self_rating_check CHECK (((self_rating >= 1) AND (self_rating <= 10)));
ALTER TABLE ONLY public.candidate_skill_map ADD CONSTRAINT candidate_skill_map_skill_id_fkey FOREIGN KEY (skill_id) REFERENCES skill_master(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.candidate_skill_map ADD CONSTRAINT candidate_skill_map_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.candidate_skill_map ADD CONSTRAINT candidate_skill_map_candidate_id_skill_id_key UNIQUE (candidate_id, skill_id);
ALTER TABLE ONLY public.client_department ADD CONSTRAINT fk_client_department_client_name_id FOREIGN KEY (client_name_id) REFERENCES client_master(id);
ALTER TABLE ONLY public.client_department ADD CONSTRAINT client_department_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.client_department ADD CONSTRAINT client_department_airtable_id_key UNIQUE (airtable_id);
ALTER TABLE ONLY public.client_master ADD CONSTRAINT fk_client_master_location_id FOREIGN KEY (location_id) REFERENCES locations(id) ON DELETE SET NULL;
ALTER TABLE ONLY public.client_master ADD CONSTRAINT client_master_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.client_master ADD CONSTRAINT client_master_airtable_id_key UNIQUE (airtable_id);
ALTER TABLE ONLY public.difficulties ADD CONSTRAINT difficulties_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.difficulties ADD CONSTRAINT difficulties_level_name_key UNIQUE (level_name);
ALTER TABLE ONLY public.locations ADD CONSTRAINT locations_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.locations ADD CONSTRAINT locations_airtable_id_key UNIQUE (airtable_id);
ALTER TABLE ONLY public.naukri_candidates ADD CONSTRAINT naukri_candidates_folder_id_fkey FOREIGN KEY (folder_id) REFERENCES naukri_folders(id) ON DELETE SET NULL;
ALTER TABLE ONLY public.naukri_candidates ADD CONSTRAINT naukri_candidates_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.naukri_folders ADD CONSTRAINT naukri_folders_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.naukri_folders ADD CONSTRAINT naukri_folders_folder_id_key UNIQUE (folder_id);
ALTER TABLE ONLY public.onboarding_events ADD CONSTRAINT onboarding_events_event_type_check CHECK (((event_type)::text = ANY ((ARRAY['vendor_onboarding'::character varying, 'xpo_onboarding'::character varying, 'client_onboarding'::character varying, 'end_client_onboarding'::character varying, 'bgv'::character varying, 'bgv_doc_submission'::character varying, 'sow_signing'::character varying, 'crc_confirmation'::character varying])::text[])));
ALTER TABLE ONLY public.onboarding_events ADD CONSTRAINT onboarding_events_selected_id_fkey FOREIGN KEY (selected_id) REFERENCES selected_candidates(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.onboarding_events ADD CONSTRAINT onboarding_events_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.onboarding_events ADD CONSTRAINT unique_selected_event UNIQUE (selected_id, event_type);
ALTER TABLE ONLY public.openai_call_logs ADD CONSTRAINT openai_call_logs_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.openings ADD CONSTRAINT fk_openings_client_department_id FOREIGN KEY (client_department_id) REFERENCES client_department(id);
ALTER TABLE ONLY public.openings ADD CONSTRAINT fk_openings_client_id FOREIGN KEY (client_id) REFERENCES client_master(id);
ALTER TABLE ONLY public.openings ADD CONSTRAINT openings_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.openings ADD CONSTRAINT openings_airtable_id_key UNIQUE (airtable_id);
ALTER TABLE ONLY public.openings_locations_openings ADD CONSTRAINT openings_locations_openings_locations_id_fkey FOREIGN KEY (locations_id) REFERENCES locations(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.openings_locations_openings ADD CONSTRAINT openings_locations_openings_openings_id_fkey FOREIGN KEY (openings_id) REFERENCES openings(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.openings_locations_openings ADD CONSTRAINT openings_locations_openings_pkey PRIMARY KEY (openings_id, locations_id);
ALTER TABLE ONLY public.profiles_database ADD CONSTRAINT fk_profiles_database_location_id FOREIGN KEY (location_id) REFERENCES locations(id);
ALTER TABLE ONLY public.profiles_database ADD CONSTRAINT fk_profiles_database_vendors_id FOREIGN KEY (vendors_id) REFERENCES vendor_master(id);
ALTER TABLE ONLY public.profiles_database ADD CONSTRAINT profiles_database_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.profiles_database ADD CONSTRAINT profiles_database_airtable_id_key UNIQUE (airtable_id);
ALTER TABLE ONLY public.questions ADD CONSTRAINT questions_difficulty_id_fkey FOREIGN KEY (difficulty_id) REFERENCES difficulties(id);
ALTER TABLE ONLY public.questions ADD CONSTRAINT questions_skill_id_fkey FOREIGN KEY (skill_id) REFERENCES skill_master(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.questions ADD CONSTRAINT questions_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.ranking_jobs ADD CONSTRAINT ranking_jobs_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.rooms ADD CONSTRAINT rooms_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.screener_assignments ADD CONSTRAINT screener_assignments_role_check CHECK (((role)::text = ANY ((ARRAY['screener'::character varying, 'tech_screener'::character varying, 'form_filler'::character varying])::text[])));
ALTER TABLE ONLY public.screener_assignments ADD CONSTRAINT screener_assignments_application_id_fkey FOREIGN KEY (application_id) REFERENCES applications_id(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.screener_assignments ADD CONSTRAINT screener_assignments_screener_id_fkey FOREIGN KEY (screener_id) REFERENCES screeners_profile(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.screener_assignments ADD CONSTRAINT screener_assignments_pkey PRIMARY KEY (screener_id, application_id, role);
ALTER TABLE ONLY public.screeners_profile ADD CONSTRAINT fk_screeners_profile_vendor_id FOREIGN KEY (vendor_id) REFERENCES vendor_master(id) ON DELETE SET NULL;
ALTER TABLE ONLY public.screeners_profile ADD CONSTRAINT screeners_profile_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.screeners_profile ADD CONSTRAINT screeners_profile_airtable_id_key UNIQUE (airtable_id);
ALTER TABLE ONLY public.screenings ADD CONSTRAINT fk_screenings_application_id FOREIGN KEY (application_id) REFERENCES applications_id(id);
ALTER TABLE ONLY public.screenings ADD CONSTRAINT fk_screenings_candidate_id FOREIGN KEY (candidate_id) REFERENCES profiles_database(id);
ALTER TABLE ONLY public.screenings ADD CONSTRAINT fk_screenings_vendor_id FOREIGN KEY (vendor_id) REFERENCES vendor_master(id);
ALTER TABLE ONLY public.screenings ADD CONSTRAINT screenings_room_id_fkey FOREIGN KEY (room_id) REFERENCES rooms(id) ON DELETE SET NULL;
ALTER TABLE ONLY public.screenings ADD CONSTRAINT screenings_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.screenings ADD CONSTRAINT screenings_airtable_id_key UNIQUE (airtable_id);
ALTER TABLE ONLY public.selected_candidates ADD CONSTRAINT fk_selected_candidates_candidate_from_applications_id FOREIGN KEY (candidate_from_applications_id) REFERENCES applications_id(id);
ALTER TABLE ONLY public.selected_candidates ADD CONSTRAINT fk_selected_candidates_whose_bench_id FOREIGN KEY (whose_bench_id) REFERENCES vendor_master(id);
ALTER TABLE ONLY public.selected_candidates ADD CONSTRAINT selected_candidates_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.selected_candidates ADD CONSTRAINT selected_candidates_airtable_id_key UNIQUE (airtable_id);
ALTER TABLE ONLY public.skill_level_master ADD CONSTRAINT skill_level_master_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.skill_level_master ADD CONSTRAINT skill_level_master_level_key UNIQUE (level);
ALTER TABLE ONLY public.skill_map ADD CONSTRAINT skill_map_level_id_fkey FOREIGN KEY (level_id) REFERENCES skill_level_master(id) ON DELETE SET NULL;
ALTER TABLE ONLY public.skill_map ADD CONSTRAINT skill_map_skill_id_fkey FOREIGN KEY (skill_id) REFERENCES skill_master(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.skill_map ADD CONSTRAINT skill_map_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.skill_map ADD CONSTRAINT skill_map_opening_id_skill_id_key UNIQUE (opening_id, skill_id);
ALTER TABLE ONLY public.skill_master ADD CONSTRAINT skill_master_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.skill_master ADD CONSTRAINT skill_master_skill_name_key UNIQUE (skill_name);
ALTER TABLE ONLY public.skill_sets ADD CONSTRAINT skill_sets_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.skill_sets ADD CONSTRAINT skill_sets_skill_name_key UNIQUE (skill_name);
ALTER TABLE ONLY public.status_config ADD CONSTRAINT status_config_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.status_config ADD CONSTRAINT status_config_domain_code_key UNIQUE (domain, code);
ALTER TABLE ONLY public.users ADD CONSTRAINT fk_users_screener_profile_id FOREIGN KEY (screener_profile_id) REFERENCES screeners_profile(id) ON DELETE SET NULL;
ALTER TABLE ONLY public.users ADD CONSTRAINT users_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.users ADD CONSTRAINT users_airtable_id_key UNIQUE (airtable_id);
ALTER TABLE ONLY public.vendor_master ADD CONSTRAINT vendor_master_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.vendor_master ADD CONSTRAINT vendor_master_airtable_id_key UNIQUE (airtable_id);
ALTER TABLE ONLY public.vendor_openings ADD CONSTRAINT vendor_openings_opening_id_fkey FOREIGN KEY (opening_id) REFERENCES openings(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.vendor_openings ADD CONSTRAINT vendor_openings_vendor_id_fkey FOREIGN KEY (vendor_id) REFERENCES vendor_master(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.vendor_openings ADD CONSTRAINT vendor_openings_pkey PRIMARY KEY (vendor_id, opening_id);

-- Indexes

CREATE INDEX idx_applications_id_airtable_id ON public.applications_id USING btree (airtable_id);
CREATE INDEX idx_applications_id_status ON public.applications_id USING btree (status);
CREATE INDEX idx_applications_id_vendor_id ON public.applications_id USING btree (vendor_id);
CREATE INDEX idx_applications_id_openings_id ON public.applications_id USING btree (openings_id);
CREATE INDEX idx_candidate_skill_map_candidate_id ON public.candidate_skill_map USING btree (candidate_id);
CREATE INDEX idx_client_department_airtable_id ON public.client_department USING btree (airtable_id);
CREATE INDEX idx_client_master_airtable_id ON public.client_master USING btree (airtable_id);
CREATE INDEX idx_locations_airtable_id ON public.locations USING btree (airtable_id);
CREATE INDEX idx_naukri_candidates_folder_id ON public.naukri_candidates USING btree (folder_id);
CREATE INDEX idx_naukri_candidates_unique_id ON public.naukri_candidates USING btree (unique_candidate_id);
CREATE INDEX idx_naukri_candidates_status ON public.naukri_candidates USING btree (status);
CREATE INDEX idx_naukri_folders_folder_id ON public.naukri_folders USING btree (folder_id);
CREATE INDEX idx_naukri_folders_vendor_id_number ON public.naukri_folders USING btree (vendor_id_number);
CREATE INDEX idx_naukri_folders_opening_id ON public.naukri_folders USING btree (opening_id);
CREATE INDEX idx_onboarding_events_selected ON public.onboarding_events USING btree (selected_id);
CREATE INDEX idx_openai_logs_timestamp ON public.openai_call_logs USING btree ("timestamp" DESC);
CREATE INDEX idx_openai_logs_status ON public.openai_call_logs USING btree (status);
CREATE INDEX idx_openai_logs_operation ON public.openai_call_logs USING btree (operation);
CREATE INDEX idx_openai_logs_candidate_id ON public.openai_call_logs USING btree (candidate_id);
CREATE INDEX idx_openings_airtable_id ON public.openings USING btree (airtable_id);
CREATE INDEX idx_openings_status ON public.openings USING btree (status);
CREATE INDEX idx_openings_sync_status ON public.openings USING btree (sync_status) WHERE (sync_status <> 'SYNCED'::text);
CREATE INDEX idx_openings_locations_openings_source ON public.openings_locations_openings USING btree (openings_id);
CREATE INDEX idx_openings_locations_openings_target ON public.openings_locations_openings USING btree (locations_id);
CREATE INDEX idx_profiles_database_airtable_id ON public.profiles_database USING btree (airtable_id);
CREATE INDEX idx_profiles_database_candidate_id ON public.profiles_database USING btree (candidate_id);
CREATE INDEX idx_profiles_database_vendors_id ON public.profiles_database USING btree (vendors_id);
CREATE INDEX idx_ranking_jobs_job_id ON public.ranking_jobs USING btree (job_id);
CREATE INDEX idx_ranking_jobs_status ON public.ranking_jobs USING btree (status);
CREATE INDEX idx_screener_assignments_application ON public.screener_assignments USING btree (application_id);
CREATE INDEX idx_screener_assignments_screener ON public.screener_assignments USING btree (screener_id);
CREATE INDEX idx_screeners_profile_airtable_id ON public.screeners_profile USING btree (airtable_id);
CREATE INDEX idx_screeners_profile_vendor_id ON public.screeners_profile USING btree (vendor_id);
CREATE INDEX idx_screenings_airtable_id ON public.screenings USING btree (airtable_id);
CREATE INDEX idx_screenings_date ON public.screenings USING btree (date);
CREATE INDEX idx_screenings_status ON public.screenings USING btree (status);
CREATE INDEX idx_screenings_room_id ON public.screenings USING btree (room_id);
CREATE INDEX idx_selected_candidates_airtable_id ON public.selected_candidates USING btree (airtable_id);
CREATE INDEX idx_skill_map_opening_id ON public.skill_map USING btree (opening_id);
CREATE INDEX idx_users_airtable_id ON public.users USING btree (airtable_id);
CREATE INDEX idx_users_screener_profile_id ON public.users USING btree (screener_profile_id);
CREATE INDEX idx_vendor_master_airtable_id ON public.vendor_master USING btree (airtable_id);
CREATE INDEX idx_vendor_master_status ON public.vendor_master USING btree (status);
CREATE INDEX idx_vendor_openings_opening ON public.vendor_openings USING btree (opening_id);
CREATE INDEX idx_vendor_openings_vendor ON public.vendor_openings USING btree (vendor_id);

-- Functions

CREATE OR REPLACE FUNCTION public.get_next_naukri_candidate_id()
 RETURNS text
 LANGUAGE plpgsql
AS $function$
DECLARE
    next_val BIGINT;
BEGIN
    next_val := nextval('naukri_candidate_id_seq');
    RETURN 'NC' || LPAD(next_val::TEXT, 5, '0');
END;
$function$

CREATE OR REPLACE FUNCTION public.nanoid(size integer DEFAULT 21, alphabet text DEFAULT '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ_'::text)
 RETURNS text
 LANGUAGE plpgsql
AS $function$
DECLARE
  idBuilder text := '';
  i int := 0;
  bytes bytea;
  alphabetIndex int;
  mask int;
  step int;
BEGIN
  mask := (2 << cast(floor(log(length(alphabet) - 1) / log(2)) as int)) - 1;
  step := cast(ceil(1.6 * mask * size / length(alphabet)) as int);
  while true loop
    bytes := gen_random_bytes(size);
    while i < size loop
      alphabetIndex := (get_byte(bytes, i) & mask) + 1;
      if alphabetIndex <= length(alphabet) then
        idBuilder := idBuilder || substr(alphabet, alphabetIndex, 1);
        if length(idBuilder) = size then
          return idBuilder;
        end if;
      end if;
      i := i + 1;
    end loop;
    i := 0;
  end loop;
END
$function$

CREATE OR REPLACE FUNCTION public.update_modified_column()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$function$

CREATE OR REPLACE FUNCTION public.update_tokens_updated_at()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$function$

CREATE OR REPLACE FUNCTION public.update_updated_at_column()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$function$


-- Triggers

CREATE TRIGGER tokens_updated_at_trigger BEFORE UPDATE ON app_tokens FOR EACH ROW EXECUTE FUNCTION update_tokens_updated_at();
CREATE TRIGGER trg_applications_id_updated_at BEFORE UPDATE ON applications_id FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_campaign_subscription_modtime BEFORE UPDATE ON campaign_subscription FOR EACH ROW EXECUTE FUNCTION update_modified_column();
CREATE TRIGGER update_campaign_trigger_modtime BEFORE UPDATE ON campaign_trigger FOR EACH ROW EXECUTE FUNCTION update_modified_column();
CREATE TRIGGER trg_client_department_updated_at BEFORE UPDATE ON client_department FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_client_master_updated_at BEFORE UPDATE ON client_master FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_locations_updated_at BEFORE UPDATE ON locations FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_naukri_candidates_updated_at BEFORE UPDATE ON naukri_candidates FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_naukri_folders_updated_at BEFORE UPDATE ON naukri_folders FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_onboarding_events_updated_at BEFORE UPDATE ON onboarding_events FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_openings_updated_at BEFORE UPDATE ON openings FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_profiles_database_updated_at BEFORE UPDATE ON profiles_database FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_rooms_updated_at BEFORE UPDATE ON rooms FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_screeners_profile_updated_at BEFORE UPDATE ON screeners_profile FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_screenings_updated_at BEFORE UPDATE ON screenings FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_selected_candidates_updated_at BEFORE UPDATE ON selected_candidates FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_status_config_updated_at BEFORE UPDATE ON status_config FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_users_updated_at BEFORE UPDATE ON users FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_vendor_master_updated_at BEFORE UPDATE ON vendor_master FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- Row Level Security

ALTER TABLE public.applications_id ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.client_department ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.client_master ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.locations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.openai_call_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.openings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles_database ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.screeners_profile ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.screenings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.selected_candidates ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vendor_master ENABLE ROW LEVEL SECURITY;

-- Policies

CREATE POLICY "Allow anon insert on applications_id" ON public.applications_id AS PERMISSIVE FOR INSERT TO anon WITH CHECK (true);
CREATE POLICY "Allow anon select on applications_id" ON public.applications_id AS PERMISSIVE FOR SELECT TO anon USING (true);
CREATE POLICY "Allow anon select on client_department" ON public.client_department AS PERMISSIVE FOR SELECT TO anon USING (true);
CREATE POLICY "Allow anon select on locations" ON public.locations AS PERMISSIVE FOR SELECT TO anon USING (true);
CREATE POLICY "Allow anon select on openings" ON public.openings AS PERMISSIVE FOR SELECT TO anon USING (true);
CREATE POLICY "Allow anon select on openings_locations_openings" ON public.openings_locations_openings AS PERMISSIVE FOR SELECT TO anon USING (true);
CREATE POLICY "Allow anon insert on profiles_database" ON public.profiles_database AS PERMISSIVE FOR INSERT TO anon WITH CHECK (true);
CREATE POLICY "Allow anon select on profiles_database" ON public.profiles_database AS PERMISSIVE FOR SELECT TO anon USING (true);
CREATE POLICY "Allow anon update on profiles_database" ON public.profiles_database AS PERMISSIVE FOR UPDATE TO anon USING (true) WITH CHECK (true);
CREATE POLICY "Allow anon select on vendor_master" ON public.vendor_master AS PERMISSIVE FOR SELECT TO anon USING (true);
